=== EESHWAR-MATURU/Web-applications/planes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://cs.uccs.edu/planeSchema"
            xmlns="http://cs.uccs.edu/planeSchema"
            elementFormDefault="qualified">
    <xsd:element name="planes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="make" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="year">
        <xsd:simpleType>
            <xsd:restriction base="xsd:decimal">
                <xsd:minInclusive value="1900"/>
                <xsd:maxInclusive value="2007"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:complexType name="sports_car">
        <xsd:sequence>
            <xsd:element name="make" type="xsd:string"/>
            <xsd:element name="model" type="xsd:string"/>
            <xsd:element name="engine" type="xsd:string"/>
            <xsd:element ref="year"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== EESHWAR-MATURU/Web-applications/XML/planes.xml
<?xml version="1.0" encoding ="utf-8"?>
<!-- planes.xml
A simple XML document for illustrating a schema The schema is in planes.xsd
-->
<planes
xmlns="http://cs.uccs.edu/planeSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://cs.uccs.edu/planeSchema 
                    planes.xsd">
<make> Eeshwar </make>
<make> Lalit </make>
<make> Siddarth </make>
</planes>
<sports_car>
<make>Ferrari</make>
<model>Testarossa</model>
<engine>V12</engine>
<year>1990</year>
</sports_car>
