=== EESHWAR-MATURU/Web-applications/student.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (id, name, email, Phone, age, grade)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (fn, ln)>
<!ELEMENT fn (#PCDATA)>
<!ELEMENT ln (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

=== EESHWAR-MATURU/Web-applications/Student.xml
<?xml-stylesheet type="text/css" href="Student.css" ?>
<!DOCTYPE student SYSTEM "student.dtd">
<students>
    <student>
        <id>1</id>
        <name>Eeshwar</name>
        <email>ematuru@gitam.in</email>
        <Phone>9346769679</Phone>
        <age>20</age>
        <grade>A+</grade>
    </student>
    <student>
        <id>2</id>
        <name>Keerthi</name>
        <email>keerthi@gitam.in</email>
        <Phone>9753689653</Phone>
        <age>20</age>
        <grade>A+</grade>
    </student>
    <student>
        <id>3</id>
        <name>Siddarth</name>
        <email>devara@gitam.in</email>
        <Phone>8765808647</Phone>
        <age>20</age>
        <grade>B</grade>
    </student>
    <student>
        <id>4</id>
        <name>Shreya</name>
        <email>Shreya@gitam.in</email>
        <Phone>9753567975</Phone>
        <age>20</age>
        <grade>A</grade>
    </student>
    <student>
        <id>5</id>
        <name>Lalith</name>
        <email>Lalith@gitam.in</email>
        <Phone>9463846382</Phone>
        <age>19</age>
        <grade>B+</grade>
    </student>
    <student>
        <id>6</id>
        <name>Amith</name>
        <email>amith@gitam.in</email>
        <Phone>9265828463</Phone>
        <age>19</age>
        <grade>B+</grade>
    </student>
</students>

=== EESHWAR-MATURU/Web-applications/XML/Student.xml
<?xml-stylesheet type="text/css" href="Student.css" ?>
<!DOCTYPE student SYSTEM "student.dtd">
<students>
    <student>
        <id>1</id>
        <name>
            <fn>Eeshwar</fn>
            <ln>Maturu</ln>
        </name>
        <email>ematuru@gitam.in</email>
        <Phone>9346769679</Phone>
        <age>20</age>
        <grade>A+</grade>
    </student>
    <student>
        <id>2</id>
        <name>
            <fn>Keerthi</fn>
            <ln>Potluri</ln>
        </name>
        <email>keerthi@gitam.in</email>
        <Phone>9753689653</Phone>
        <age>20</age>
        <grade>A+</grade>
    </student>
    <student>
        <id>3</id>
        <name>
            <fn>Siddarth</fn>
            <ln>Devara</ln>
        </name>
        <email>devara@gitam.in</email>
        <Phone>8765808647</Phone>
        <age>20</age>
        <grade>B</grade>
    </student>
    <student>
        <id>4</id>
        <name>
            <fn>Shreya</fn>
            <ln>Somaraju</ln>
        </name>
        <email>Shreya@gitam.in</email>
        <Phone>9753567975</Phone>
        <age>20</age>
        <grade>A</grade>
    </student>
    <student>
        <id>5</id>
        <name>
            <fn>Lalit</fn>
            <ln>Narayanam</ln>
        </name>
        <email>Lalit@gitam.in</email>
        <Phone>9463846382</Phone>
        <age>19</age>
        <grade>B+</grade>
    </student>
    <student>
        <id>6</id>
        <name>
            <fn>Amith</fn>
            <ln>Komaravelli</ln>
        </name>
        <email>amith@gitam.in</email>
        <Phone>9265828463</Phone>
        <age>19</age>
        <grade>B+</grade>
    </student>
</students>
